# 版本: 2026.3.13
调试模式: false

目标服务器: MMORPG

传送门:
  MMORPG:
    世界: login_world
    最小X: 5
    最小Y: 18
    最小Z: 5
    最大X: 10
    最大Y: 24
    最大Z: 10
    目标服务器: MMORPG
    提示消息: '&a正在传送至MMORPG服...'
  粘液科技:
    世界: login_world
    最小X: -10
    最小Y: 18
    最小Z: 5
    最大X: -5
    最大Y: 24
    最大Z: 10
    目标服务器: 粘液科技
    提示消息: '&a正在传送至粘液科技服...'
  多元生存:
    世界: login_world
    最小X: 5
    最小Y: 18
    最小Z: -10
    最大X: 10
    最大Y: 24
    最大Z: -5
    目标服务器: 多元生存
    提示消息: '&a正在传送至多元生存服...'

数据库:
  主机: localhost
  端口: 3306
  数据库名: 燃烧之陨
  用户名: root
  密码: BXYXblupz542284

重生点:
  世界: login_world
  X: 8.0
  Y: 21.0
  Z: 8.0
  偏航: 0
  俯仰: 0
